---
title: "EDA"
author: "Jin Wen Lin"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
#fmri data
library(readr)
library(dplyr)
tsv_files <- list.files("train_tsv", pattern = "\\.tsv$", full.names = TRUE)
extract_upper_tri <- function(file_path) {
  mat <- as.matrix(read_tsv(file_path, col_names = FALSE))
  upper_tri <- mat[upper.tri(mat, diag = FALSE)]  
  return(upper_tri)
}
patient_data <- t(sapply(tsv_files, extract_upper_tri))
patient_df <- as.data.frame(patient_data)
rownames(patient_df) <- basename(tsv_files)
library(tibble)
patient_df <- rownames_to_column(patient_df, var = "participant_id")
fmri <- patient_df
fmri$participant_id <- substr(fmri$participant_id, 5, 16)
fmri$participant_id <- sub("_.*", "", fmri$participant_id)
```

```{r}
library(dplyr)
#metadata
meta_train <- read.csv("metadata/training_metadata.csv")
meta_test <- read.csv("metadata/test_metadata.csv")
#missing values of meta_train
colSums(is.na(meta_train))
#class of meta_train
sapply(meta_train, class)
#data cleaning
library(dplyr)
#impute bmi by sex
bmi_means <- meta_train %>%
  group_by(sex) %>%
  summarise(bmi_mean = mean(bmi, na.rm = TRUE))
meta_train <- meta_train %>%
  left_join(bmi_means, by = "sex") %>%
  mutate(
    bmi = ifelse(is.na(bmi), bmi_mean, bmi)  
  ) %>%
  select(-bmi_mean) 
#turn NAs into Missing
meta_train <- meta_train %>%
  mutate(across(where(is.character), ~ ifelse(is.na(.), "Missing", .)))
#same for test data
meta_test <- meta_test %>%
  left_join(bmi_means, by = "sex") %>%
  mutate(
    bmi = ifelse(is.na(bmi), bmi_mean, bmi) 
  ) %>%
  select(-bmi_mean)  
meta_test <- meta_test %>%
  mutate(across(where(is.character), ~ ifelse(is.na(.), "Missing", .)))

# all the numeric varaibkes from metadata (except age)
num_cols <- names(meta_train)[sapply(meta_train, is.numeric)]
num_cols <- setdiff(num_cols, "age")

# 2. mean and sd
train_means <- sapply(meta_train[num_cols], mean, na.rm = TRUE)
train_sds   <- sapply(meta_train[num_cols], sd,   na.rm = TRUE)

# 3. standardize
meta_train <- meta_train %>%
  mutate(across(
    all_of(num_cols),
    ~ (. - train_means[cur_column()]) / train_sds[cur_column()]
  ))
#same for test data
meta_test <- meta_test %>%
  left_join(bmi_means, by = "sex") %>%
  mutate(
    bmi = ifelse(is.na(bmi), bmi_mean, bmi) 
  ) %>%
  select(-bmi_mean)  
meta_test <- meta_test %>%
  mutate(across(where(is.character), ~ ifelse(is.na(.), "Missing", .)))

cols_to_scale_test <- intersect(num_cols, names(meta_test))

meta_test <- meta_test %>%
  mutate(across(
    all_of(cols_to_scale_test),
    ~ (. - train_means[cur_column()]) / train_sds[cur_column()]
  ))
```

```{r}
lapply(
  meta_train[, sapply(meta_train, is.character) & names(meta_train) != "participant_id"],
  unique
)
```

## EDA

```{r}
library(ggplot2)
library(gridExtra)

# sex distribution
d1 <- ggplot(meta_train, aes(x = sex, fill = sex)) + 
  geom_bar(color = "black") + theme_minimal() +
  ggtitle("Sex Distribution")


# age distribution
d2 <- ggplot(meta_train, aes(x = age)) + 
  geom_histogram(bins = 30, fill = "skyblue", color = "black") + theme_minimal() +
  ggtitle("Age Distribution")

grid.arrange(d1, d2, ncol = 2)
```

```{r}
# Age by study site
d3 <- ggplot(meta_train, aes(x = study_site, y = age, fill = study_site)) + 
  geom_boxplot() + 
  ggtitle("Age by Study Site") + theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Study Site")

# Age by sex
d4 <- ggplot(meta_train, aes(x = sex, y = age, fill = sex)) +
  geom_boxplot(color = "black") + theme_minimal() +
  labs(title = "Age by Sex", x = "Sex", y = "Age")


grid.arrange(d3, d4, ncol = 2)
```

```{r}
# BMI visualizations
d5 <- ggplot(meta_train, aes(x = age, y = bmi, color = sex)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "loess", se = FALSE, color = "black") +
  theme_minimal() +
  labs(title = "BMI vs Age by Sex", x = "Age", y = "BMI")

d6 <- ggplot(meta_train, aes(x = sex, y = bmi, fill = sex)) +
  geom_boxplot(color = "black") +
  scale_fill_manual(values = c("Male" = "lightblue", "Female" = "pink")) +
  theme_minimal() +
  labs(title = "BMI by Sex", x = "Sex", y = "BMI")
grid.arrange(d5, d6, ncol = 2)
```

```{r}
library(tidyr)
# Parent Education
edu_long <- meta_train %>%
  pivot_longer(cols = c(parent_1_education, parent_2_education),
               names_to = "Parent",
               values_to = "Education")

p6 <- ggplot(edu_long, aes(x = Education, fill = Parent)) +
  geom_bar(position = "dodge", color = "black") +
  scale_fill_brewer(palette = "Set1")+
  theme_minimal() +
  labs(title = "Parent Education Levels", x = "Education Level", y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```

```{r}
# ethnicity
p7 <- ggplot(meta_train, aes(x = ethnicity, fill = ethnicity)) +
  geom_bar(color = "black") +
  theme_minimal() +
  labs(title = "Ethnicity Distribution", x = "Ethnicity", y = "Count")+ 
  scale_fill_brewer(palette = "Set2") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# race
p8 <- ggplot(meta_train, aes(x = race, fill = race)) +
  geom_bar(color = "black") +
  theme_minimal() +
  labs(title = "Race Distribution", x = "Race", y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# handedness
p9 <- ggplot(meta_train, aes(x = handedness, fill = handedness)) +
  geom_bar(color = "black") +
  theme_minimal() +
  labs(title = "Handedness Distribution", x = "Handedness", y = "Count")


grid.arrange(p6, p7, p8, p9, ncol = 2)
```

## Mental health factors

```{r}
library(reshape2)
# distribution of mental health factors
mh_long <- melt(meta_train[, c("p_factor_fs", "internalizing_fs", 
                               "externalizing_fs", "attention_fs")])

ggplot(mh_long, aes(x = value, fill = variable)) +
  geom_density(alpha = 0.5, color = "black") +
  theme_minimal() +
  labs(title = "Distribution of Mental Health Factors", x = "Z-Score", y = "Density") +
  scale_fill_brewer(palette = "Set2", name = "Factor")  

```

```{r}
library(corrplot)
# correlation of mental health factors
mh_cor <- cor(meta_train[, c("p_factor_fs", "internalizing_fs", 
                             "externalizing_fs", "attention_fs", "age")], use = "complete.obs")
corrplot(mh_cor, method = "color", type = "upper", addCoef.col = "black",
         tl.col = "black", tl.srt = 45, col = colorRampPalette(c("white", "blue"))(200))


```
